using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IoTClient
{
    static class Data
    {
        public static string[] Sentences =
        {
            "On an exceptionally hot evening early in July a young man came out of the garret in which he lodged in S. Place and walked slowly, as though in hesitation, towards K. bridge.",
            "He had successfully avoided meeting his landlady on the staircase. His garret was under the roof of a high, five-storied house and was more like a cupboard than a room.",
            "The landlady who provided him with garret, dinners, and attendance, lived on the floor below, and every time he went out he was obliged to pass her kitchen, the door of which invariably stood open.",
            "And each time he passed, the young man had a sick, frightened feeling, which made him scowl and feel ashamed. He was hopelessly in debt to his landlady, and was afraid of meeting her.",
            "This was not because he was cowardly and abject, quite the contrary; but for some time past he had been in an overstrained irritable condition, verging on hypochondria.",
            "He had become so completely absorbed in himself, and isolated from his fellows that he dreaded meeting, not only his landlady, but anyone at all.",
            "He was crushed by poverty, but the anxieties of his position had of late ceased to weigh upon him. He had given up attending to matters of practical importance; he had lost all desire to do so.",
            "Nothing that any landlady could do had a real terror for him. But to be stopped on the stairs, to be forced to listen to her trivial, irrelevant gossip, to pestering demands for payment, threats and complaints, and to rack his brains for excuses, to prevaricate, to lie - no, rather than that, he would creep down the stairs like a cat and slip out unseen.",
            "This evening, however, on coming out into the street, he became acutely aware of his fears.",
            "'I want to attempt a thing like that and am frightened by these trifles,' he thought, with an odd smile. 'Hm... yes, all is in a man's hands and he lets it all slip from cowardice, that's an axiom.",
            "It would be interesting to know what it is men are most afraid of. Taking a new step, uttering a new word is what they fear most. But I am talking too much. It's because I chatter that I do nothing. Or perhaps it is that I chatter because I do nothing.",
            "I've learned to chatter this last month, lying for days together in my den thinking of Jack the Giant-killer. Why am I going there now? Am I capable of that? Is that serious? It is not serious at all. It's simply a fantasy to amuse myself; a plaything! Yes, maybe it is a plaything.'",
            "The heat in the street was terrible: and the airlessness, the bustle and the plaster, scaffolding, bricks, and dust all about him, and that special Petersburg stench, so familiar to all who are unable to get out of town in summer-all worked painfully upon the young man's already overwrought nerves.",
            "The insufferable stench from the pothouses, which are particularly numerous in that part of the town, and the drunken men whom he met continually, although it was a working day, completed the revolting misery of the picture. An expression of the profoundest disgust gleamed for a moment in the young man's refined face.",
            "He was, by the way, exceptionally handsome, above the average in height, slim, well-built, with beautiful dark eyes and dark brown hair.",
            "Soon he sank into deep thought, or more accurately speaking into a complete blankness of mind; he walked along not observing what was about him and not caring to observe it. From time to time, he would mutter something, from the habit of talking to himself, to which he had just confessed.",
            "At these moments he would become conscious that his ideas were sometimes in a tangle and that he was very weak; for two days he had scarcely tasted food.",
            "He was so badly dressed that even a man accustomed to shabbiness would have been ashamed to be seen in the street in such rags. In that quarter of the town, however, scarcely any shortcoming in dress would have created surprise.",
            "Owing to the proximity of the Hay Market, the number of establishments of bad character, the preponderance of the trading and working class population crowded in these streets and alleys in the heart of Petersburg, types so various were to be seen in the streets that no figure, however queer, would have caused surprise.",
            "But there was such accumulated bitterness and contempt in the young man's heart, that, in spite of all the fastidiousness of youth, he minded his rags least of all in the street. It was a different matter when he met with acquaintances or with former fellow students, whom, indeed, he disliked meeting at any time.",
            "And yet when a drunken man who, for some unknown reason, was being taken somewhere in a huge waggon dragged by a heavy dray horse, suddenly shouted at him as he drove past:",
            "'Hey there, German hatter' bawling at the top of his voice and pointing at him - the young man stopped suddenly and clutched tremulously at his hat. It was a tall round hat from Zimmerman's, but completely worn out, rusty with age, all torn and bespattered, brimless and bent on one side in a most unseemly fashion. Not shame, however, but quite another feeling akin to terror had overtaken him.",
            "'I knew it,' he muttered in confusion, 'I thought so! That's the worst of all! Why, a stupid thing like this, the most trivial detail might spoil the whole plan. Yes, my hat is too noticeable. It looks absurd and that makes it noticeable. With my rags I ought to wear a cap, any sort of old pancake, but not this grotesque thing.",
            "Nobody wears such a hat, it would be noticed a mile off, it would be remembered. What matters is that people would remember it, and that would give them a clue. For this business one should be as little conspicuous as possible. Trifles, trifles are what matter! Why, it's just such trifles that always ruin everything.'",
            "He had not far to go; he knew indeed how many steps it was from the gate of his lodging house: exactly seven hundred and thirty. He had counted them once when he had been lost in dreams. At the time he had put no faith in those dreams and was only tantalising himself by their hideous but daring recklessness.",
            "Now, a month later, he had begun to look upon them differently, and, in spite of the monologues in which he jeered at his own impotence and indecision, he had involuntarily come to regard this 'hideous' dream as an exploit to be attempted, although he still did not realise this himself. He was positively going now for a 'rehearsal' of his project, and at every step his excitement grew more and more violent.",
            "With a sinking heart and a nervous tremor, he went up to a huge house which on one side looked on to the canal, and on the other into the street. This house was let out in tiny tenements and was inhabited by working people of all kinds - tailors, locksmiths, cooks, Germans of sorts, girls picking up a living as best they could, petty clerks, etc. There was a continual coming and going through the two gates and in the two courtyards of the house.",
            "Three or four door-keepers were employed on the building. The young man was very glad to meet none of them, and at once slipped unnoticed through the door on the right, and up the staircase. It was a back staircase, dark and narrow, but he was familiar with it already, and knew his way, and he liked all these surroundings: in such darkness even the most inquisitive eyes were not to be dreaded.",
            "'If I am so scared now, what would it be if it somehow came to pass that I were really going to do it?' he could not help asking himself as he reached the fourth storey. There his progress was barred by some porters who were engaged in moving furniture out of a flat.",
            "He knew that the flat had been occupied by a German clerk in the civil service, and his family. This German was moving out then, and so the fourth floor on this staircase would be untenanted except by the old woman. 'That's a good thing anyway,' he thought to himself, as he rang the bell of the old woman's flat.",
            "The bell gave a faint tinkle as though it were made of tin and not of copper. The little flats in such houses always have bells that ring like that. He had forgotten the note of that bell, and now its peculiar tinkle seemed to remind him of something and to bring it clearly before him. He started, his nerves were terribly overstrained by now.",
            "In a little while, the door was opened a tiny crack: the old woman eyed her visitor with evident distrust through the crack, and nothing could be seen but her little eyes, glittering in the darkness. But, seeing a number of people on the landing, she grew bolder, and opened the door wide. The young man stepped into the dark entry, which was partitioned off from the tiny kitchen. The old woman stood facing him in silence and looking inquiringly at him.",
            "She was a diminutive, withered up old woman of sixty, with sharp malignant eyes and a sharp little nose. Her colourless, somewhat grizzled hair was thickly smeared with oil, and she wore no kerchief over it.",
            "Round her thin long neck, which looked like a hen's leg, was knotted some sort of flannel rag, and, in spite of the heat, there hung flapping on her shoulders, a mangy fur cape, yellow with age.",
            "The old woman coughed and groaned at every instant. The young man must have looked at her with a rather peculiar expression, for a gleam of mistrust came into her eyes again.",
            "'Raskolnikov, a student, I came here a month ago,' the young man made haste to mutter, with a half bow, remembering that he ought to be more polite.",
            "'I remember, my good sir, I remember quite well your coming here,' the old woman said distinctly, still keeping her inquiring eyes on his face.",
            "'And here I am again on the same errand,' Raskolnikov continued, a little disconcerted and surprised at the old woman's mistrust. 'Perhaps she is always like that though, only I did not notice it the other time,' he thought with an uneasy feeling.",
            "The old woman paused, as though hesitating; then stepped on one side, and pointing to the door of the room, she said, letting her visitor pass in front of her:",
            "'Step in, my good sir.'",
            "The little room into which the young man walked, with yellow paper on the walls, geraniums and muslin curtains in the windows, was brightly lighted up at that moment by the setting sun.",
            "'So the sun will shine like this then too!' flashed as it were by chance through Raskolnikov's mind, and with a rapid glance he scanned everything in the room, trying as far as possible to notice and remember its arrangement.",
            "But there was nothing special in the room. The furniture, all very old and of yellow wood, consisted of a sofa with a huge bent wooden back, an oval table in front of the sofa, a dressing-table with a looking-glass fixed on it between the windows, chairs along the walls and two or three half-penny prints in yellow frames, representing German damsels with birds in their hands-that was all.",
            "In the corner a light was burning before a small ikon. Everything was very clean; the floor and the furniture were brightly polished; everything shone.",
            "'Lizaveta's work,' thought the young man. There was not a speck of dust to be seen in the whole flat.",
            "'It's in the houses of spiteful old widows that one finds such cleanliness,' Raskolnikov thought again, and he stole a curious glance at the cotton curtain over the door leading into another tiny room, in which stood the old woman's bed and chest of drawers and into which he had never looked before. These two rooms made up the whole flat.",
            "'What do you want?' the old woman said severely, coming into the room and, as before, standing in front of him so as to look him straight in the face.",
            "'I've brought something to pawn here,' and he drew out of his pocket an old-fashioned flat silver watch, on the back of which was engraved a globe; the chain was of steel.",
            "'But the time is up for your last pledge. The month was up the day before yesterday.'",
            "'I will bring you the interest for another month; wait a little.'",
            "'But that's for me to do as I please, my good sir, to wait or to sell your pledge at once.'",
            "'How much will you give me for the watch, Alyona Ivanovna?'",
            "'You come with such trifles, my good sir, it's scarcely worth anything. I gave you two roubles last time for your ring and one could buy it quite new at a jeweler's for a rouble and a half.'",
            "'Give me four roubles for it, I shall redeem it, it was my father's. I shall be getting some money soon.'",
            "'A rouble and a half, and interest in advance, if you like!'",
            "'A rouble and a half!' cried the young man.",
            "'Please yourself - and the old woman handed him back the watch. The young man took it, and was so angry that he was on the point of going away; but checked himself at once, remembering that there was nowhere else he could go, and that he had had another object also in coming.'",
            "'Hand it over,' he said roughly.",
            "The old woman fumbled in her pocket for her keys, and disappeared behind the curtain into the other room. The young man, left standing alone in the middle of the room, listened inquisitively, thinking. He could hear her unlocking the chest of drawers.",
            "'It must be the top drawer,' he reflected. 'So she carries the keys in a pocket on the right. All in one bunch on a steel ring. And there's one key there, three times as big as all the others, with deep notches; that can't be the key of the chest of drawers then there must be some other chest or strong-box that's worth knowing. Strong-boxes always have keys like that but how degrading it all is.'",
            "The old woman came back.",
            "'Here, sir: as we say ten copecks the rouble a month, so I must take fifteen copecks from a rouble and a half for the month in advance. But for the two roubles I lent you before, you owe me now twenty copecks on the same reckoning in advance. That makes thirty - five copecks altogether. So I must give you a rouble and fifteen copecks for the watch. Here it is.'",
            "'What! Only a rouble and fifteen copecks now!'",
            "'Just so.'",
            "The young man did not dispute it and took the money. He looked at the old woman, and was in no hurry to get away, as though there was still something he wanted to say or to do, but he did not himself quite know what.",
            "'I may be bringing you something else in a day or two, Alyona Ivanovna - a valuable thing-silver-a cigarette-box, as soon as I get it back from a friend he broke off in confusion.",
            "'Well, we will talk about it then, sir.'",
            "'Good-bye-are you always at home alone, your sister is not here with you?' He asked her as casually as possible as he went out into the passage.",
            "'What business is she of yours, my good sir?'",
            "'Oh, nothing particular, I simply asked. You are too quick. Good day, Alyona Ivanovna.'",
            "Raskolnikov went out in complete confusion. This confusion became more and more intense. As he went down the stairs, he even stopped short, two or three times, as though suddenly struck by some thought. When he was in the street he cried out,",
            "'Oh, God, how loathsome it all is and can I, can I possibly. No, it's nonsense, it's rubbish!' he added resolutely. 'And how could such an atrocious thing come into my head? What filthy things my heart is capable of. Yes, filthy above all, disgusting, loathsome, loathsome! - and for a whole month I've been.'",
            "But no words, no exclamations, could express his agitation. The feeling of intense repulsion, which had begun to oppress and torture his heart while he was on his way to the old woman, had by now reached such a pitch and had taken such a definite form that he did not know what to do with himself to escape from his wretchedness.",
            "He walked along the pavement like a drunken man, regardless of the passers- by, and jostling against them, and only came to his senses when he was in the next street.",
            "Looking round, he noticed that he was standing close to a tavern which was entered by steps leading from the pavement to the basement. At that instant two drunken men came out at the door, and abusing and supporting one another, they mounted the steps.",
            "Without stopping to think, Raskolnikov went down the steps at once. Till that moment he had never been into a tavern, but now he felt giddy and was tormented by a burning thirst.",
            "He longed for a drink of cold beer, and attributed his sudden weakness to the want of food. He sat down at a sticky little table in a dark and dirty corner; ordered some beer, and eagerly drank off the first glassful. At once he felt easier; and his thoughts became clear.",
            "'All that's nonsense,' he said hopefully, 'and there is nothing in it all to worry about! It's simply physical derangement. Just a glass of beer, a piece of dry bread - and in one moment the brain is stronger, the mind is clearer and the will is firm! Phew, how utterly petty it all is!'",
            "'He met the one he used to know.'",
            "But in spite of this scornful reflection, he was by now looking cheerful as though he were suddenly set free from a terrible burden: and he gazed round in a friendly way at the people in the room. But even at that moment he had a dim foreboding that this happier frame of mind was also not normal.",
            "There were few people at the time in the tavern. Besides the two drunken men he had met on the steps, a group consisting of about five men and a girl with a concertina had gone out at the same time.",
            "Their departure left the room quiet and rather empty. The persons still in the tavern were a man who appeared to be an artisan, drunk, but not extremely so, sitting before a pot of beer, and his companion, a huge, stout man with a grey beard, in a short full- skirted coat. He was very drunk: and had dropped asleep on the bench; every now and then, he began as though in his sleep, cracking his fingers, with his arms wide apart and the upper part of his body bounding about on the bench, while he hummed some meaningless refrain, trying to recall some such lines as these:",
            "'His wife a year he fondly loved His wife a-a year he - fondly loved.'",
            "Or suddenly waking up again:",
            "'Walking along the crowded row",
            "But no one shared his enjoyment: his silent companion looked with positive hostility and mistrust at all these manifestations. There was another man in the room who looked somewhat like a retired government clerk. He was sitting apart, now and then sipping from his pot and looking round at the company. He, too, appeared to be in some agitation.",
            "The master of the establishment was in another room, but he frequently came down some steps into the main room, his jaunty, tarred boots with red turn-over tops coming into view each time before the rest of his person.",
            "He wore a full coat and a horribly greasy black satin waistcoat, with no cravat, and his whole face seemed smeared with oil like an iron lock.",
            "At the counter stood a boy of about fourteen, and there was another boy somewhat younger who handed whatever was wanted. On the counter lay some sliced cucumber, some pieces of dried black bread, and some fish, chopped up small, all smelling very bad.",
            "It was insufferably close, and so heavy with the fumes of spirits that five minutes in such an atmosphere might well make a man drunk.",
            "There are chance meetings with strangers that interest us from the first moment, before a word is spoken. Such was the impression made on Raskolnikov by the person sitting a little distance from him, who looked like a retired clerk.",
            "The young man often recalled this impression afterwards, and even ascribed it to presentiment. He looked repeatedly at the clerk, partly no doubt because the latter was staring persistently at him, obviously anxious to enter into conversation.",
            "At the other persons in the room, including the tavern- keeper, the clerk looked as though he were used to their company, and weary of it, showing a shade of condescending contempt for them as persons of station and culture inferior to his own, with whom it would be useless for him to converse.",
            "He was a man over fifty, bald and grizzled, of medium height, and stoutly built. His face, bloated from continual drinking, was of a yellow, even greenish, tinge, with swollen eyelids out of which keen reddish eyes gleamed like little chinks. But there was something very strange in him; there was a light in his eyes as though of intense feeling - perhaps there were even thought and intelligence, but at the same time there was a gleam of something like madness.",
            "He was wearing an old and hopelessly ragged black dress coat, with all its buttons missing except one, and that one he had buttoned, evidently clinging to this last trace of respectability.",
            "A crumpled shirt front, covered with spots and stains, protruded from his canvas waistcoat. Like a clerk, he wore no beard, nor moustache, but had been so long unshaven that his chin looked like a stiff greyish brush.",
            "And there was something respectable and like an official about his manner too. But he was restless; he ruffled up his hair and from time to time let his head drop into his hands dejectedly resting his ragged elbows on the stained and sticky table. At last he looked straight at Raskolnikov, and said loudly and resolutely:",
            "'May I venture, honoured sir, to engage you in polite conversation? Forasmuch as, though your exterior would not command respect, my experience admonishes me that you are a man of education and not accustomed to drinking. I have always respected education when in conjunction with genuine sentiments, and I am besides a titular counsellor in rank. Marmeladov - such is my name; titular counsellor. I make bold to inquire-have you been in the service?'",
            "'No, I am studying,' answered the young man, somewhat surprised at the grandiloquent style of the speaker and also at being so directly addressed.",
            "In spite of the momentary desire he had just been feeling for company of any sort, on being actually spoken to he felt immediately his habitual irritable and uneasy aversion for any stranger who approached or attempted to approach him.",
            "'A student then, or formerly a student,' cried the clerk. 'Just what I thought! I'm a man of experience, immense experience, sir,' and he tapped his forehead with his fingers in self-approval. 'You've been a student or have attended some learned institution! But allow me.'",
            "He got up, staggered, took up his jug and glass, and sat down beside the young man, facing him a little sideways. He was drunk, but spoke fluently and boldly, only occasionally losing the thread of his sentences and drawling his words.",
            "He pounced upon Raskolnikov as greedily as though he too had not spoken to a soul for a month.",
            "'Honoured sir,' he began almost with solemnity, 'poverty is not a vice, that's a true saying. Yet I know too that drunkenness is not a virtue, and that that's even truer. But beggary, honoured sir, beggary is a vice.",
            "In poverty you may still retain your innate nobility of soul, but in beggary - never-no one.",
            "For beggary a man is not chased out of human society with a stick, he is swept out with a broom, so as to make it as humiliating as possible; and quite right, too, forasmuch as in beggary I am ready to be the first to humiliate myself.",
            "Hence the pot-house! Honoured sir, a month ago Mr. Lebeziatnikov gave my wife a beating, and my wife is a very different matter from me!",
            "Do you understand? Allow me to ask you another question out of simple curiosity: have you ever spent a night on a hay barge, on the Neva?'",
            "'No, I have not happened to,' answered Raskolnikov. 'What do you mean?'",
            "'Well, I've just come from one and it's the fifth night I've slept so.'",
            "He filled his glass, emptied it and paused. Bits of hay were in fact clinging to his clothes and sticking to his hair. It seemed quite probable that he had not undressed or washed for the last five days. His hands, particularly, were filthy. They were fat and red, with black nails.",
            "His conversation seemed to excite a general though languid interest. The boys at the counter fell to sniggering. The innkeeper came down from the upper room, apparently on purpose to listen to the 'funny fellow' and sat down at a little distance, yawning lazily, but with dignity.",
            "Evidently Marmeladov was a familiar figure here, and he had most likely acquired his weakness for high- flown speeches from the habit of frequently entering into conversation with strangers of all sorts in the tavern. This habit develops into a necessity in some drunkards, and especially in those who are looked after sharply and kept in order at home.",
            "Hence in the company of other drinkers they try to justify themselves and even if possible obtain consideration.",
            "'Funny fellow!' pronounced the innkeeper. 'And why don't you work, why aren't you at your duty, if you are in the service?'",
            "'Why am I not at my duty, honoured sir,' Marmeladov went on, addressing himself exclusively to Raskolnikov, as though it had been he who put that question to him. 'Why am I not at my duty?",
            "Does not my heart ache to think what a useless worm I am? A month ago when Mr. Lebeziatnikov beat my wife with his own hands, and I lay drunk, didn't I suffer? Excuse me, young man, has it ever happened to you well, to petition hopelessly for a loan?'",
            "'Yes, it has. But what do you mean by hopelessly?'",
            "'Hopelessly in the fullest sense, when you know beforehand that you will get nothing by it. You know, for instance, beforehand with positive certainty that this man, this most reputable and exemplary citizen, will on no consideration give you money; and indeed I ask you why should he? For he knows of course that I shan't pay it back. From compassion? But Mr. Lebeziatnikov who keeps up with modern ideas explained the other day that compassion is forbidden nowadays by science itself, and that that's what is done now in England, where there is political economy. Why, I ask you, should he give it to me? And yet though I know beforehand that he won't, I set off to him and.'",
            "'Why do you go?' put in Raskolnikov.",
            "'Well, when one has no one, nowhere else one can go! For every man must have somewhere to go. Since there are times when one absolutely must go somewhere! When my own daughter first went out with a yellow ticket, then I had to go (for my daughter has a yellow passport),' he added in parenthesis, looking with a certain uneasiness at the young man.",
            "'No matter, sir, no matter!' he went on hurriedly and with apparent composure when both the boys at the counter guffawed and even the innkeeper smiled.",
            "'No matter, for everyone knows everything about it already, and all that is secret is made open. And I accept it all, not with contempt, but with humility. So be it! So be it! 'Behold the man!' Excuse me, young man, can you no, to put it more strongly and more distinctly, not can you but dare you, looking upon me, assert that I am not a pig?'",
            "The young man did not answer a word.",
            "'Well,' the orator began again stolidly and with even increased dignity, after waiting for the laughter in the room to subside. 'Well, so be it, I am a pig, but she is a lady! I have the semblance of a beast, but Katerina Ivanovna, my spouse, is a person of education and an officer's daughter.",
            "Granted, granted, I am a scoundrel, but she is a woman of a noble heart, full of sentiments, refined by education. And yet oh, if only she felt for me! Honoured sir, honoured sir, you know every man ought to have at least one place where people feel for him! But Katerina Ivanovna, though she is magnanimous, she is unjust. And yet, although I realise that when she pulls my hair she only does it out of pity-for I repeat without being ashamed, she pulls my hair, young man,' he declared with redoubled dignity, hearing the sniggering again-",
            "'But, my God, if she would but once. But no, no! It's all in vain and it's no use talking! No use talking! For more than once, my wish did come true and more than once she has felt for me but, such is my fate and I am a beast by nature!'",
            "'Rather!' assented the innkeeper yawning. Marmeladov struck his fist resolutely on the table.",
            "'Such is my fate! Do you know, sir, do you know, I have sold her very stockings for drink? Not her shoes-that would be more or less in the order of things, but her stockings, her stockings I have sold for drink! Her mohair shawl I sold for drink, a present to her long ago, her own property, not mine; and we live in a cold room and she caught cold this winter and has begun coughing and spitting blood too.",
            "We have three little children and Katerina Ivanovna is at work from morning till night; she is scrubbing and cleaning and washing the children, for she's been used to cleanliness from a child. But her chest is weak and she has a tendency to consumption and I feel it! Do you suppose I don't feel it? And the more I drink the more I feel it. That's why I drink too. I try to find sympathy and feeling in drink. I drink so that I may suffer twice as much!' And as though in despair he laid his head down on the table.",
            "'Young man,' he went on, raising his head again, 'in your face I seem to read some trouble of mind. When you came in I read it, and that was why I addressed you at once. For in unfolding to you the story of my life, I do not wish to make myself a laughing-stock before these idle listeners, who indeed know all about it already, but I am looking for a man of feeling and education.",
            "Know then that my wife was educated in a high-class school for the daughters of noblemen, and on leaving she danced the shawl dance before the governor and other personages for which she was presented with a gold medal and a certificate of merit. The medal well, the medal of course was sold - long ago, but the certificate of merit is in her trunk still and not long ago she showed it to our landlady.",
            "And although she is most continually on bad terms with the landlady, yet she wanted to tell someone or other of her past honours and of the happy days that are gone. I don't condemn her for it, I don't blame her, for the one thing left her is recollection of the past, and all the rest is dust and ashes. Yes, yes, she is a lady of spirit, proud and determined. She scrubs the floors herself and has nothing but black bread to eat, but won't allow herself to be treated with disrespect.",
            "That's why she would not overlook Mr. Lebeziatnikov's rudeness to her, and so when he gave her a beating for it, she took to her bed more from the hurt to her feelings than from the blows. She was a widow when I married her, with three children, one smaller than the other. She married her first husband, an infantry officer, for love, and ran away with him from her father's house.",
            "She was exceedingly fond of her husband; but he gave way to cards, got into trouble and with that he died. He used to beat her at the end: and although she paid him back, of which I have authentic documentary evidence, to this day she speaks of him with tears and she throws him up to me; and I am glad, I am glad that, though only in imagination, she should think of herself as having once been happy.",
            "And she was left at his death with three children in a wild and remote district where I happened to be at the time; and she was left in such hopeless poverty that, although I have seen many ups and downs of all sort, I don't feel equal to describing it even. Her relations had all thrown her off. And she was proud, too, excessively proud.",
            "And then, honoured sir, and then, I, being at the time a widower, with a daughter of fourteen left me by my first wife, offered her my hand, for I could not bear the sight of such suffering. You can judge the extremity of her calamities, that she, a woman of education and culture and distinguished family, should have consented to be my wife. But she did!",
            "Weeping and sobbing and wringing her hands, she married me! For she had nowhere to turn! Do you understand, sir, do you understand what it means when you have absolutely nowhere to turn?",
            "'No, that you don't understand yet. And for a whole year, I performed my duties conscientiously and faithfully, and did not touch this' (he tapped the jug with his finger), 'for I have feelings. But even so, I could not please her; and then I lost my place too, and that through no fault of mine but through changes in the office; and then I did touch it!",
            "It will be a year and a half ago soon since we found ourselves at last after many wanderings and numerous calamities in this magnificent capital, adorned with innumerable monuments. Here I obtained a situation. I obtained it and I lost it again. Do you understand? This time it was through my own fault I lost it: for my weakness had come out.",
            "We have now part of a room at Amalia Fyodorovna Lippevechsel's; and what we live upon and what we pay our rent with, I could not say. There are a lot of people living there besides ourselves. Dirt and disorder, a perfect Bedlam hm... yes.",
            "And meanwhile my daughter by my first wife has grown up; and what my daughter has had to put up with from her step-mother whilst she was growing up, I won't speak of. For, though Katerina Ivanovna is full of generous feelings, she is a spirited lady, irritable and short - tempered.",
            "Yes. But it's no use going over that! Sonia, as you may well fancy, has had no education. I did make an effort four years ago to give her a course of geography and universal history, but as I was not very well up in those subjects myself and we had no suitable books, and what books we had, anyway we have not even those now, so all our instruction came to an end.",
            "We stopped at Cyrus of Persia. Since she has attained years of maturity, she has read other books of romantic tendency and of late she had read with great interest a book she got through Mr. Lebeziatnikov, Lewes' Physiology- do you know it? - and even recounted extracts from it to us: and that's the whole of her education. And now may I venture to address you, honoured sir, on my own account with a private question.",
            "Do you suppose that a respectable poor girl can earn much by honest work?",
            "Not fifteen farthings a day can she earn, if she is respectable and has no special talent and that without putting her work down for an instant! And what's more, Ivan Ivanitch Klopstock the civil counsellor - have you heard of him? - has not to this day paid her for the half-dozen linen shirts she made him and drove her roughly away, stamping and reviling her, on the pretext that the shirt collars were not made like the pattern and were put in askew.",
            "And there are the little ones hungry.",
            "And Katerina Ivanovna walking up and down and wringing her hands, her cheeks flushed red, as they always are in that disease: 'Here you live with us,' says she, 'you eat and drink and are kept warm and you do nothing to help.' And much she gets to eat and drink when there is not a crust for the little ones for three days! I was lying at the time well, what of it!",
            "I was lying drunk and I heard my Sonia speaking (she is a gentle creature with a soft little voice fair hair and such a pale, thin little face). She said: 'Katerina Ivanovna, am I really to do a thing like that?'",
            "And Darya Frantsovna, a woman of evil character and very well known to the police, had two or three times tried to get at her through the landlady.",
            "'And why not?' said Katerina Ivanovna with a jeer, 'you are something mighty precious to be so careful of!' But don't blame her, don't blame her, honoured sir, don't blame her! She was not herself when she spoke, but driven to distraction by her illness and the crying of the hungry children; and it was said more to wound her than anything else.",
            "For that's Katerina Ivanovna's character, and when children cry, even from hunger, she falls to beating them at once. At six o'clock I saw Sonia get up, put on her kerchief and her cape, and go out of the room and about nine o'clock she came back. She walked straight up to Katerina Ivanovna and she laid thirty roubles on the table before her in silence.",
            "She did not utter a word, she did not even look at her, she simply picked up our big green drap de dames shawl (we have a shawl, made of drap de dames) put it over her head and face and lay down on the bed with her face to the wall; only her little shoulders and her body kept shuddering.",
            "And I went on lying there, just as before. And then I saw, young man, I saw Katerina Ivanovna, in the same silence go up to Sonia's little bed; she was on her knees all the evening kissing Sonia's feet, and would not get up, and then they both fell asleep in each other's arms together, together yes and I lay drunk.'",
            "Marmeladov stopped short, as though his voice had failed him. Then he hurriedly filled his glass, drank, and cleared his throat.",
            "'Since then, sir,' he went on after a brief pause--'Since then, owing to an unfortunate occurrence and through information given by evil - intentioned persons-in all which Darya Frantsovna took a leading part on the pretext that she had been treated with want of respect - since then my daughter Sofya Semyonovna has been forced to take a yellow ticket, and owing to that she is unable to go on living with us.",
            "For our landlady, Amalia Fyodorovna would not hear of it (though she had backed up Darya Frantsovna before) and Mr. Lebeziatnikov too. All the trouble between him and Katerina Ivanovna was on Sonia's account. At first he was for making up to Sonia himself and then all of a sudden he stood on his dignity:",
            "'How,' said he, 'can a highly educated man like me live in the same rooms with a girl like that?' And Katerina Ivanovna would not let it pass, she stood up for her and so that's how it happened. And Sonia comes to us now, mostly after dark; she comforts Katerina Ivanovna and gives her all she can.",
        };
        public static string[] Words = {
            "about",
            "after",
            "again",
            "air",
            "all",
            "along",
            "also",
            "an",
            "and",
            "another",
            "any",
            "are",
            "around",
            "as",
            "at",
            "away",
            "back",
            "be",
            "because",
            "been",
            "before",
            "below",
            "between",
            "both",
            "but",
            "by",
            "came",
            "can",
            "come",
            "could",
            "day",
            "did",
            "different",
            "do",
            "does",
            "don't",
            "down",
            "each",
            "end",
            "even",
            "every",
            "few",
            "find",
            "first",
            "for",
            "found",
            "from",
            "get",
            "give",
            "go",
            "good",
            "great",
            "had",
            "has",
            "have",
            "he",
            "help",
            "her",
            "here",
            "him",
            "his",
            "home",
            "house",
            "how",
            "I",
            "if",
            "in",
            "into",
            "is",
            "it",
            "its",
            "just",
            "know",
            "large",
            "last",
            "left",
            "like",
            "line",
            "little",
            "long",
            "look",
            "made",
            "make",
            "man",
            "many",
            "may",
            "me",
            "men",
            "might",
            "more",
            "most",
            "Mr.",
            "must",
            "my",
            "name",
            "never",
            "new",
            "next",
            "no",
            "not",
            "now",
            "number",
            "of",
            "off",
            "old",
            "on",
            "one",
            "only",
            "or",
            "other",
            "our",
            "out",
            "over",
            "own",
            "part",
            "people",
            "place",
            "put",
            "read",
            "right",
            "said",
            "same",
            "saw",
            "say",
            "see",
            "she",
            "should",
            "show",
            "small",
            "so",
            "some",
            "something",
            "sound",
            "still",
            "such",
            "take",
            "tell",
            "than",
            "that",
            "the",
            "them",
            "then",
            "there",
            "these",
            "they",
            "thing",
            "think",
            "this",
            "those",
            "thought",
            "three",
            "through",
            "time",
            "to",
            "together",
            "too",
            "two",
            "under",
            "up",
            "us",
            "use",
            "very",
            "want",
            "water",
            "way",
            "we",
            "well",
            "went",
            "were",
            "what",
            "when",
            "where",
            "which",
            "while",
            "who",
            "why",
            "will",
            "with",
            "word",
            "work",
            "world",
            "would",
            "write",
            "year",
            "you",
            "your",
            "was"
        };
    }
}
